<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // 1. Convert status column to string to make it easier to manage constraints in PostgreSQL
        Schema::table('purchases', function (Blueprint $table) {
            $table->string('status')->default('received')->change();
        });

        // 2. Drop the existing enum check constraint (standard name generated by Laravel/Doctrine)
        // We use try-catch or direct SQL to be safe on various environments
        try {
            DB::statement("ALTER TABLE purchases DROP CONSTRAINT purchases_status_check");
        } catch (\Exception $e) {
            // Constraint might not exist or have a different name in some environments
        }

        // 3. Add the new expanded status check constraint
        DB::statement("ALTER TABLE purchases ADD CONSTRAINT purchases_status_check 
            CHECK (status IN ('pending', 'pending_approval', 'pending_confirmation', 'received', 'approved', 'completed', 'cancelled'))");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        try {
            DB::statement("ALTER TABLE purchases DROP CONSTRAINT purchases_status_check");
        } catch (\Exception $e) {}

        DB::statement("ALTER TABLE purchases ADD CONSTRAINT purchases_status_check 
            CHECK (status IN ('received', 'pending_confirmation'))");
    }
};
